name: WakaTime Readme Stats

on:
  schedule:
    - cron: "0 * * * *"   # runs every hour
  workflow_dispatch:       # allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: athul/waka-readme@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
